### ISSUE TITLE
Redemption should not trigger when the board is full

### ISSUE THREAD

**Issue by danielyule** [danielyule/hearthbreaker#92]
If a Harvest Golem dies on a full board, its deathrattle will go off first, placing the damaged golem on the board.  Redemption won't fire, because the board is full.  Currently not sure how to handle both this and #91

**Comment by anka-213** [comment]
You could do something like this: 7f37c813b46c. I don't quite like it as it complicates the triggering in `die()`, but mostly because it makes the code in `ApplySecret` specific to Mad Scientist. Though, the latter can possibly be fixed by using a better name ( than `"minion_dead"`) for the event  I introduced.

**Comment by anka-213** [comment]
The idea is to trigger deathrattles before secrets, but delaying the activation of the secret Mad Scientist played, so it doesn't trigger on itself.

**Comment by danielyule** [comment]
This is probably the best solution.  I had been thinking I'd have to add tracking of who caused the deathrattle into the secret, but this is cleaner.  I fixed it up a bit, to make it more generic, but it works great.
